/* Chief Gear prototype. Cost catalogue from the public WoSTools calculator. */
(function(){'use strict';
const stages=window.FOX_GEAR_DATA.stages,keys=['hardenedAlloy','polishingSolution','designPlans','lunarAmber'];
const resources=[{key:keys[0],name:'Hardened Alloy',img:'item-hardened-alloy.png'},{key:keys[1],name:'Polishing Solution',img:'item-polishing-solution.png'},{key:keys[2],name:'Design Plans',img:'item-design-plans.png'},{key:keys[3],name:'Lunar Amber',img:'item-lunar-amber.png'}];
const pieces=[['jacket','Jacket','Infantry'],['pants','Pants','Infantry'],['helmet','Helmet','Lancer'],['watch','Watch','Lancer'],['ring','Ring','Marksman'],['cane','Cane','Marksman']];
const fmt=n=>Number(n).toLocaleString('en-GB'),index=id=>stages.findIndex(s=>s.id===id);
function cost(from,to){if(!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<from||to>=stages.length)throw Error('Invalid gear range');const x={hardenedAlloy:0,polishingSolution:0,designPlans:0,lunarAmber:0,score:0,steps:to-from,power:stages[to].power-stages[from].power};for(let n=from+1;n<=to;n++){keys.forEach(k=>x[k]+=stages[n][k]);x.score+=stages[n].score;}x.points=x.score*36;return x;}
window.FOXGear={cost,mount(host,api){
let saved=api.plan,disposed=false,revision=0,savedRevision=0,saving=false,saveTimer=null,requestedMode;let draft=[];let mode=saved&&saved.view==='saved'?'saved':'edit';requestedMode=mode;let plan=pieces.map(p=>{let r=saved&&Array.isArray(saved.rows)&&saved.rows.find(r=>r.id===p[0]);let from=r?index(r.from):0,to=r?index(r.to):0;if(from<0||to<from){from=0;to=0;}return {...{id:p[0],name:p[1],troop:p[2]},from,to};});
let stock={};
const icon=r=>'<img src="'+r.img+'" width="20" height="20" alt="">',material=c=>resources.filter(r=>c[r.key]>0).map(r=>'<span title="'+r.name+'">'+icon(r)+fmt(c[r.key])+'</span>').join('')||'<small>No upgrades planned</small>';
host.innerHTML='<div class="gear-intro"><h2>Plan your Chief Gear upgrades.</h2><p>Choose each piece’s current tier and target. Turn your plan into Backpack targets.</p></div><div class="gear-layout"><section><div class="gear-card"><header class="gear-heading"><h3>My Chief Gear <small>6 pieces</small></h3><div class="gear-mode"><button id="cg-edit">Edit</button><button id="cg-save">Save</button><span>PERSONAL PLAN</span></div></header><div class="gear-bulk"><label for="cg-bulk">Set all targets</label><select id="cg-bulk"></select><button id="cg-bulkapply">Apply to all</button></div><div id="cg-rows"></div></div><p class="gear-note" id="cg-save-status" role="status">Choose your current and target tiers. Your plan is saved to your account.</p><button id="cg-retry" hidden>Retry saving plan</button><details class="gear-card gear-help"><summary>How will this update my Backpack?</summary><p>Required totals replace the relevant material targets. Your stock stays unchanged. Materials with zero required cost keep their existing targets. Exchanges already planned in your Backpack are reflected in Have; this calculator does not plan additional exchanges.</p><p>Plans are saved to your account. Review the replacement targets before applying.</p></details><p class="gear-note">Costs and estimated SvS scores: <a href="https://wostools.net/chief-gear-calculator" target="_blank" rel="noopener">WoSTools reference</a> · Through Red T4 3★, including partial stages. Verify available tiers in your state.</p></section><aside><div class="gear-card gear-summary"><h3>Your plan needs</h3><p class="gear-note" id="cg-count"></p><div id="cg-materials"></div><p class="gear-note">Whole-plan costs before subtracting your stock.</p><button class="gear-primary" id="cg-push">Push to Backpack as Target</button><p class="gear-note gear-center">Review each target before applying.</p><p id="cg-status" role="status" class="gear-note"></p></div><div class="gear-card"><header class="gear-heading"><h3>Backpack targets</h3></header><div class="gear-body" id="cg-targets"></div></div><div class="gear-card"><header class="gear-heading"><h3>Estimated SvS points</h3></header><div class="gear-body"><strong class="gear-points" id="cg-points"></strong><span> pts</span><p class="gear-note" id="cg-formula"></p><p class="gear-note">Estimate if all planned gear upgrades are completed during the eligible SvS phase. Excludes charms, speedups and event bonuses.</p></div></div></aside></div><dialog id="cg-confirm" aria-labelledby="cg-title"><h3 id="cg-title">Update your Backpack targets?</h3><p>Replace these material targets with your plan totals.</p><div id="cg-changes"></div><p class="gear-note">Your current stock stays unchanged.</p><p id="cg-error" role="alert"></p><div class="gear-dialog-actions"><button id="cg-cancel">Keep current targets</button><button class="gear-primary" id="cg-apply">Apply targets</button></div></dialog>';
const $=id=>host.querySelector('#cg-'+id),options=(v,min=0)=>stages.map((s,i)=>i<min?'':'<option value="'+i+'"'+(v===i?' selected':'')+'>'+s.label+'</option>').join('');let totals;
async function persist(){if(disposed||saving||savedRevision===revision)return;saving=true;$('save').disabled=true;$('edit').disabled=true;const attempt=revision,data={version:window.FOX_GEAR_DATA.version,view:requestedMode,rows:plan.map(r=>({id:r.id,from:stages[r.from].id,to:stages[r.to].id}))};$('save-status').textContent='Saving plan…';$('retry').hidden=true;try{await api.savePlan(data);savedRevision=attempt;if(attempt===revision){mode=requestedMode;render();}$('save-status').textContent='Plan saved to your account.';}catch(e){$('save-status').textContent='Plan not saved. Check your connection and retry.';$('retry').hidden=false;}finally{saving=false;$('save').disabled=false;$('edit').disabled=false;if(!disposed&&attempt!==revision)persist();}}
function changed(){revision++;requestedMode=mode;$('save-status').textContent='Unsaved changes';clearTimeout(saveTimer);saveTimer=setTimeout(persist,500);render();}
function render(){if(disposed)return;stock=api.stock();resources.forEach(r=>{if(!stock[r.key])stock[r.key]={have:0,target:0,missing:true};});const rows=plan.map(r=>cost(r.from,r.to));totals={hardenedAlloy:0,polishingSolution:0,designPlans:0,lunarAmber:0,score:0,steps:0,power:0,points:0};rows.forEach(c=>Object.keys(totals).forEach(k=>totals[k]+=c[k]));host.classList.toggle('gear-readonly',mode==='saved');$('edit').setAttribute('aria-pressed',String(mode==='edit'));$('save').setAttribute('aria-pressed',String(mode==='saved'));$('rows').innerHTML=plan.map((r,i)=>'<div class="gear-row"><div class="gear-rowtop"><h4>'+r.name+'<small>'+r.troop+'</small></h4></div>'+(mode==='edit'?'<div class="gear-fields"><label>CURRENT TIER<select data-piece="'+i+'" data-field="from" aria-label="'+r.name+' current tier">'+options(r.from)+'</select></label><span class="gear-arrow" aria-hidden="true">→</span><label>TARGET TIER<select class="gear-target" data-piece="'+i+'" data-field="to" aria-label="'+r.name+' target tier">'+options(r.to,r.from)+'</select></label></div>':'<div class="gear-range">'+stages[r.from].label+' <span aria-hidden="true">→</span> <b>'+stages[r.to].label+'</b></div>')+'<div class="gear-rowcost">'+material(rows[i])+'</div>'+(mode==='edit'?'<p class="gear-row-note">'+rows[i].steps+' upgrade stages · '+fmt(rows[i].points)+' estimated SvS pts</p>':'')+'</div>').join('');$('count').textContent=plan.filter(r=>r.to>r.from).length+' of 6 pieces to upgrade · '+totals.steps+' stages';$('materials').innerHTML=resources.map(r=>'<div class="gear-material"><div>'+icon(r)+'<span>'+r.name+'<small>Have '+fmt(stock[r.key].have)+' · Missing '+fmt(Math.max(0,totals[r.key]-stock[r.key].have))+'</small></span></div><b>'+fmt(totals[r.key])+'</b></div>').join('');$('targets').innerHTML=resources.filter(r=>totals[r.key]>0).map(r=>'<div class="gear-target-line"><span>'+r.name+'</span><div>'+fmt(stock[r.key].target)+' <span aria-hidden="true">→</span> <b>'+fmt(totals[r.key])+'</b></div></div>').join('')||'<p class="gear-note">No target changes planned.</p>';$('points').textContent=fmt(totals.points);$('formula').textContent=fmt(totals.score)+' gear score × 36 points';$('push').disabled=totals.steps===0||resources.some(r=>totals[r.key]>0&&stock[r.key].missing);}
$('bulk').innerHTML=options(index('gold-0'));$('rows').onchange=e=>{let i=e.target.dataset.piece,f=e.target.dataset.field;if(i===undefined||!f)return;plan[i][f]=+e.target.value;if(plan[i].to<plan[i].from)plan[i].to=plan[i].from;changed();};$('bulkapply').onclick=()=>{plan.forEach(r=>r.to=Math.max(r.from,+$('bulk').value));changed();};$('save').onclick=()=>{if(saving)return;requestedMode='saved';revision++;clearTimeout(saveTimer);persist();};$('edit').onclick=()=>{if(saving)return;mode='edit';changed();};$('retry').onclick=persist;$('push').onclick=()=>{draft=resources.filter(r=>totals[r.key]>0).map(r=>({key:r.key,target:totals[r.key]}));$('error').textContent='';$('changes').innerHTML=resources.filter(r=>totals[r.key]>0).map(r=>'<div class="gear-target-line"><span>'+r.name+'</span><div>'+fmt(stock[r.key].target)+' → <b>'+fmt(totals[r.key])+'</b></div></div>').join('');$('confirm').showModal();};$('cancel').onclick=()=>$('confirm').close();$('apply').onclick=async()=>{if($('apply').disabled)return;$('apply').disabled=true;$('cancel').disabled=true;$('error').textContent='';try{await api.applyTargets(draft);$('confirm').close();render();$('status').textContent='Backpack targets updated.';}catch(e){$('error').textContent=e.message||'Targets could not be saved. Please retry.';}finally{$('apply').disabled=false;$('cancel').disabled=false;}};$('confirm').addEventListener('cancel',e=>{if($('apply').disabled)e.preventDefault();});render();return {refresh:render,dispose:()=>{disposed=true;clearTimeout(saveTimer);}};
}};
})();
